dist: trusty
sudo: false

language: scala

scala:
  - 2.12.7
  - 2.11.12

jdk: oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "lt6o077EUUYKU8Le0e1kWyeBQReavvpjWyMJ7NbLGlIcI4Y8Vxe46vhjt7B67uZstDg7/7kTAwWEkqgiuQw8TC5VcKKMOiSqgV5pyTAl3wQz4F2UbAqOHk445eDS/STX3JpLZyCAAg619huM6RoEA0dcls5D1Y6+1I9DE6ZYd9JU04Kzoter8FOjyEL5GlkO+Z8hC+hfgJZHAHRyGFmftkl1xP+tpaonJxcvev+kkm3FHVT3GDNZOoim58NWaX3xZrMz8kDViGshBqZ6rR94Q7vWxjS+iAEK7BVFxHig2TUADnQWciUiSXfhzUO51kLk2EhgeXSKA6y+FRj9xwZ1w0V1+BDAZDKYuOf8NjYZT2dN9fX2GwVQOnQRFc2+ty/2vPEWt2m2VK+LXMfnFSWqz8L16j/Q4FhXqFOuWa328gj55ytzKqfCcHMAeRZf3UQUhM6wX9refjrv+l0c5FwgLIKJV2YbxkwfKU/9ryclG6eeAHo0ZhSw4L93ydc8VY2LO0OpGgTA/7QFLZjIni5gyOjPC/ag1evnhwIaSKSGWBVRJve8CbEiuj0ay2wYhfG3R0VmOtiSu7vGl0MF3uldMYwKk3OQHAilhugZr4p+ZupUkiXJZpKh+rI6XF811NF6e0Hbas0+G3M+TpJuVqk8l+dLOgTLu7rTFwp1IvhuoQ4="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete